cert-mounter-blueprint:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  envConfig:
    APP: foo

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url

  kvCertificatesName:
    - mock-certificate
    - fake-cert
    - dev01-rtd-internal-dev-cstar-pagopa-it

  keyvault:
    name: "cstar-d-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
