# -- Namespace in which deploy the microservice
namespace: ""

# -- Helm chart name override
nameOverride: ""

# -- Helm chart fullname override
fullnameOverride: ""

#
# Deployment
#

# -- Configure deployment
# @default -- -
deployment:
  # -- (bool) create the deployment manifest
  create: true
  # -- (int) Number of replicas for this deployment
  replicas: 1

# -- image: configuration for the container
# @default -- {}
image:
  # -- Amazon ECR reposity for the container
  repository: "public.ecr.aws/docker/library/busybox"
  # -- Container TAG
  tag: "1.36.1@sha256:7edf5efe6b86dbf01ccc3c76b32a37a8e23b84e6bad81ce8ae8c221fa456fda8"
  # -- Container Digest sha256
  digest: "sha256:e246aa22ad2cbdfbd19e2a6ca2b275e26245a21920e2b2d0666324cee3f15549"
  # -- Pull policy to use
  pullPolicy: Always
# -- Configure values from config maps external to chart. E.g already present into cluster, see documentation
# @default -- {}
envConfigMapExternals: {}

# -- POD resources section
# @default -- -
resources:
  # -- request is mandatory
  requests:
    # -- memory
    memory: "30Mi"
    # -- cpu
    cpu: "10m"
  # -- limits is mandatory
  limits:
    # -- memory
    memory: "30Mi"
    # -- cpu
    cpu: "10m"

# -- Environment config to use for the canary container
envConfig: {}

# -- Environment secrets to use for the canary container
envSecret: {}

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false

# -- K8s node selectors
nodeSelector: {}

# -- Pod taints toleration
tolerations: []

# -- Pod labels affinity
affinity: {}

#
# Pod identity and KV connection
#

# -- Secrect provider class allow to connect to azure kv
# @default -- -
secretProviderClass:
  # -- (bool) create or not the secret provider class manifest
  create: true

# -- Azure KeyVault connection configuration
# @default -- -
keyvault:
  # -- KV name
  name: ""
  # -- Tenant id (uuid)
  tenantId: ""

# -- List of certificate names as present into KV azure
# @default -- []
kvCertificatesName: []

# -- Service account configuration
# @default -- -
serviceAccount:
  # -- (bool) Create the service account object. If true use this object, otherwise use only the name reference
  create: false
  # -- Service account name, this service account already exists
  name: ""
  annotations: {}
  # -- (bool)
  automount: false

azure:
  # -- (bool) Enable workload identity
  workloadIdentityEnabled: true
  # -- Azure Workload Identity Client ID (e.g. qwerty123-a1aa-1234-xyza-qwerty123)
  workloadIdentityClientId: ""
