{{- $fullName  := include "cert-mounter-blueprint.fullname" .  -}}
{{- if .Values.deployment.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-mounter-blueprint.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cert-mounter-blueprint.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "cert-mounter-blueprint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cert-mounter-blueprint.selectorLabels" . | nindent 8 }}
        {{- include "cert-mounter-blueprint.extraLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ include "cert-mounter-blueprint.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: crt-mounter
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ['tail', '-f', '/dev/null']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $kvCert := .Values.kvCertificatesName }}
            - name: secrets-crt-{{ $kvCert }}
              mountPath: "/mnt/secrets-store-crt-{{ $kvCert }}"
              readOnly: true
            {{- end }}
      volumes:

        ### TLS cert
        {{- range $kvCert := .Values.kvCertificatesName }}
        - name: secrets-crt-{{ $kvCert }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $fullName }}-{{ $kvCert }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
