{{- $fullName  := include "cert-mounter-blueprint.fullname" .  -}}
{{- range $kvCert := .Values.kvCertificatesName }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $fullName }}-{{ $kvCert }}
  namespace: {{ $.Values.namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ $kvCert | replace "." "-" }}
      type: kubernetes.io/tls
      data:
        - key: tls.key
          objectName: {{ $kvCert | replace "." "-" }}
        - key: tls.crt
          objectName: {{ $kvCert | replace "." "-" }}
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ $.Values.keyvault.name }}
    tenantId: {{ $.Values.keyvault.tenantId }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: {{ $kvCert }}
          objectType: secret
          objectVersion: ""
---
{{- end }}

